## minIO配置 （配置在nacos）
#minio:
#  url: http://127.0.0.1:9005 # ip地址
#  accessKey: admin           # 账号
#  secretKey: 12345678        # 密码
#  secure: false              # 如果是true，则用的是https而不是http,默认值是true
#  bucketName: "image"        # 桶的名字